#-------------------------------------
# GitHub Actions Part-1 - Basic
#
# CopyRight (C) mcmouse88 2022.
#-------------------------------------

name: PIPELINE
# global property
env:
  APPLICATION_NAME: "For-Jenkins"
  PACKAGE_NAME: "com.mcmouse-${{ github.sha }}"
  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
  
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello!
      run: echo "Hello World from build!"
      
    - name: Execute few commands
      run: |
        echo "Message #1"
        echo "Message #2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"

    - name: List current folder
      run: ls -la

    # clone repository on virtual machine GitHub
    - name: Git clone repo
      uses: actions/checkout@v1 

    - name: List current folder
      run: ls -la
          
  deploy:
    runs-on: ubuntu-latest
    # need for launch job after finished previous
    needs: [test]
    # local property
    env:
      VAR_ONE: "This is Job Level Variable One"
      VAR_TWO: "This is Job Level Variable Two"
    
    steps:
    - name: Print Hello!
      run: echo "Hello World from deploy!"
      
    - name: Deploy package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"

    - name: Lets test some packages
      run: aws --version

    - name: Lets test some packages
      run: zip --version

    - name: Print env vars
      run: |
        echo "var1 = ${{ env.VAR_ONE }}"
        echo "var1 = ${{ env.VAR_TWO }}"
        echo "var3 = $LOCAL_VAR"
      # step property
      env:
        LOCAL_VAR: "This is local step property"
