#-------------------------------------
# GitHub Actions Part-1 - Basic
#
# CopyRight (C) mcmouse88 2022.
#-------------------------------------

name: PIPELINE
# global property
env:
  APPLICATION_NAME: "For-Jenkins"
  PACKAGE_NAME: "com.mcmouse-${{ github.sha }}"
  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
  
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello!
      run: echo "Hello World from build!"
      
    - name: Execute few commands
      run: |
        echo "Message #1"
        echo "Message #2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
          
  deploy:
    runs-on: ubuntu-latest
    # need for launch job after finished previous
    needs: [test]
    
    steps:
    - name: Print Hello!
      run: echo "Hello World from deploy!"
      
    - name: Deploy package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
          
